In [8]:
import pandas as pd

## HYBRID QA POT

In [9]:
hybrid_pot = pd.read_csv('/Users/harshavardhank/Desktop/Code/UPenn/TTQA-Recasting/Benchmark/src/scripts/models/responses/New/hybridqa/hybridqa_pot_results.csv')

In [10]:
hybrid_pot.head()

,Unnamed: 0.1,Unnamed: 0,index,table_id,question,response,answer,output,conv_actual_answer,conv_predicted_answer,f1_score,exact
0,0,0,0,Phoenix_Coyotes_0,Arizona Coyotes player number 19 played in how...,```python\n# Define the table including the he...,21,22\n,21.0,21.0,100.0,100.0
1,1,1,1,List_of_Washington_Redskins_players_12,What was the post-secondary school attended by...,```python\n# Define the table including the he...,Agricultural and Mechanical College of Texas,ERROR,agricultural and mechanical college of texas,not enough information provided,0.0,0.0
2,2,2,2,List_of_Methodist_churches_in_the_United_States_7,"What is the name of the church whose city , st...",```python\n# Define the table including the he...,Trinity Methodist Episcopal Church,Trinity Methodist Episcopal Church\n,trinity methodist episcopal church,trinity methodist episcopal church,100.0,100.0
3,3,3,3,American_Horse_of_the_Year_0,What was the middle name of the trainer of the...,```python\n# Define the table including the he...,Mark,Asmussen\n,mark,not enough information provided,0.0,0.0
4,4,4,4,Roger_Crozier_Saving_Grace_Award_1,How many Vezina Trophies did the most recent w...,```python\n# Define the table including the he...,six,6\n,6.0,6.0,100.0,100.0

In [12]:
hybrid_pot.sample(50)

,Unnamed: 0.1,Unnamed: 0,index,table_id,question,response,answer,output,conv_actual_answer,conv_predicted_answer,f1_score,exact
205,205,205,207,2012_Southeastern_Conference_football_season_1,How many times was the university attended by ...,```python\n# Define the table including the he...,16,ERROR,16.0,16.0,100.000000,100.0
847,847,847,851,List_of_flag_bearers_for_Rwanda_at_the_Olympics_0,The 2016 flag bearer for Rwanda at the Summer ...,```python\n# Define the table including the he...,1987,ERROR,1987,not enough information provided,0.000000,0.0
773,773,773,777,UNLV_Rebels_0,What sport ( s ) did the athlete compete in wh...,```python\n# Define the table including the he...,Swimming,Swimming\n,swiing,swiing,100.000000,100.0
822,822,822,826,Cedar_Point_1,What is the company that opened a ride in the ...,```python\n# Define the table including the he...,Sansei Technologies,ERROR,sansei technologies,ride entertainment group,0.000000,0.0
1352,1352,1352,1361,Russian_Bandy_Super_League_0,Which of the bandy clubs established in 1923 h...,```python\n# Define the table including the he...,Baykal-Energiya,Baykal-Energiya\n,baykal-energiya,baykal-energiya,100.000000,100.0
401,401,401,403,2004_World_Series_of_Poker_0,"How many times has the victor in $ 2,000 Pot L...",```python\n# Define the table including the he...,three,ERROR,3.0,not enough information provided,0.000000,0.0
1406,1406,1406,1415,2015_in_sports_9,The Participant born on 7 January 1985 compete...,```python\n# Define the table including the he...,2015 Russian Grand Prix,2015 Russian Grand Prix\n,2015 russian grand prix,2015 russian grand prix,100.000000,100.0
74,74,74,74,Chris_Innis_0,Among the Apprentice Editor positions what is ...,```python\n# Define the table including the he...,William Oliver Stone,Director Oliver Stone\n,william oliver st1,director oliver st1,66.666667,0.0
1184,1184,1184,1192,List_of_New_York_University_alumni_13,After dropping out of NYU and becoming the fou...,```python\n# Define the table including the he...,11,0\n,11.0,1.0,0.000000,0.0
476,476,476,478,List_of_Baptist_churches_in_Alabama_0,"Built just after 1900 , this church is in coun...",```python\n# Define the table including the he...,First Baptist Church of Greenville,First Baptist Church of Wetumpka\n,first baptist church of greenville,first baptist church of wetumpka,80.000000,0.0
95,95,95,96,2004_Japanese_Grand_Prix_0,What series does the 14th place competitor cur...,```python\n# Define the table including the he...,Blancpain GT Series,ERROR,blancpain gt series,jaguar - cosworth,0.000000,0.0
779,779,779,783,List_of_districts_of_Jammu_and_Kashmir_1,What was the 2001 population of the district w...,```python\n# Define the table including the he...,"437,885","629,309\n",437885.0,629309.0,0.000000,0.0
1331,1331,1331,1339,List_of_video_games_published_by_Aksys_Games_5,The prequel to the 2007 game Record of Agarest...,```python\n# Define the table including the he...,Microsoft,Xbox\n,microsoft,xbox,0.000000,0.0
1012,1012,1012,1017,Hong_Kong_at_the_2010_Asian_Games_0,For the sport in which the Hong Kong athlete w...,```python\n# Define the table including the he...,2,2\n,2.0,2.0,100.000000,100.0
1511,1511,1511,1521,Club_for_Growth_6,"Did the Candidate born on March 17 , 1970 Win ...",```python\n# Define the table including the he...,Win,Win\n,win,win,100.000000,100.0
1106,1106,1106,1113,National_Register_of_Historic_Places_listings_...,"In 2010 , what was the population of the town ...",```python\n# Define the table including the he...,"20,756",ERROR,20756.0,not enough information provided,0.000000,0.0
1258,1258,1258,1266,World_record_progression_100_metres_backstroke_2,Since what century has the place where Ulrike ...,```python\n# Define the table including the he...,8th,ERROR,8.0,16.0,0.000000,0.0
937,937,937,941,1972_International_Cross_Country_Championships_1,What is the nationality of the athlete who was...,```python\n# Define the table including the he...,Italy,Italy\n,italy,italy,100.000000,100.0
914,914,914,918,National_Register_of_Historic_Places_listings_...,What type of architecture is the site in the s...,```python\n# Define the table including the he...,Beaux Arts Neo-Classical,ERROR,beaux arts neo-classical,not enough information provided,0.000000,0.0
593,593,593,596,List_of_United_States_Military_Academy_alumni_14,When did the last Brigadier General die ?,```python\n# Define the table including the he...,"September 22 , 1969",ERROR,"september 22 , 1969",not enough information provided,0.000000,0.0
1453,1453,1453,1462,List_of_University_of_South_Carolina_people_18,What was the 2019 estimated population of the ...,```python\n# Define the table including the he...,"10,617,423",ERROR,10617423.0,10617423.0,100.000000,100.0
953,953,953,957,List_of_public_art_in_Swansea_0,What kind of practice does this person promote...,```python\n# Define the table including the he...,health fraud,ERROR,health fraud,not enough information provided,0.000000,0.0
474,474,474,476,1989_Mexican_Grand_Prix_0,Which track was the site of an accident put on...,```python\n# Define the table including the he...,Brands Hatch,Gregor Foitek\n,brands hatch,gregor foitek,0.000000,0.0
395,395,395,397,"List_of_highways_in_Essex_County,_New_York_0",What is the distance in miles for the highway ...,```python\n# Define the table including the he...,67.69,ERROR,67.69,67.69,100.000000,100.0
625,625,625,628,India_at_the_1990_Commonwealth_Games_0,What date did Chandersekaran Raghavan start co...,```python\n# Define the table including the he...,24 January,Flyweight-Snatch\n,24 january,flyw8-snatch,0.000000,0.0
1226,1226,1226,1234,2001_AFL_Draft_2,Which league does this footballer who used to ...,```python\n# Define the table including the he...,Hume Football League,ERROR,hume football league,not enough information provided,0.000000,0.0
1283,1283,1283,1291,Athletics_at_the_2009_Games_of_the_Small_State...,"The athlete , born 20 January , ran the race i...",```python\n# Define the table including the he...,22.19,22.19\n,22.19,22.19,100.000000,100.0
260,260,260,262,List_of_sports_films_61,At what school did the most recent film take p...,```python\n# Define the table including the he...,Iowa City West High School,ERROR,iowa city west high school,iowa city west,75.000000,0.0
848,848,848,852,List_of_bus_transit_systems_in_the_United_Stat...,When was the county formed that is the locale ...,```python\n# Define the table including the he...,"September 25 , 1786",ERROR,"september 25 , 1786",not enough information provided,0.000000,0.0
554,554,554,556,L._League_0,What event diminished the prominence as a port...,```python\n# Define the table including the he...,1995 Great Hanshin earthquake,ERROR,1995 great hanshin earthquake,1995 great hanshin earthquake,100.000000,100.0
645,645,645,648,NCAA_Division_I_conference_realignment_8,What was the former conference of the school f...,```python\n# Define the table including the he...,Independent,Independent\n,independent,independent,100.000000,100.0
1077,1077,1077,1084,Kentucky_Jockey_Club_Stakes_0,What year did a jockey win the Preakness Stake...,```python\n# Define the table including the he...,2011,2013\n,2011,2013,0.000000,0.0
30,30,30,30,List_of_Pacific-12_Conference_national_champio...,What is the number of NCAA Team Championships ...,```python\n# Define the table including the he...,107,107\n,107.0,107.0,100.000000,100.0
294,294,294,296,5th_Legislative_Assembly_of_Saskatchewan_0,What is the party for the member in the electo...,```python\n# Define the table including the he...,Independent,Independent\n,independent,independent,100.000000,100.0
1029,1029,1029,1034,List_of_Baptist_churches_17,What was the population of this town in 2010 w...,```python\n# Define the table including the he...,423,ERROR,423.0,not enough information provided,0.000000,0.0
842,842,842,846,National_parks_of_France_0,How many miles are protected in the park estab...,```python\n# Define the table including the he...,"7,840 sq mi",ERROR,"7,840 sq mi","13,089",0.000000,0.0
1218,1218,1218,1226,Live!_with_Regis_and_Kelly_(Season_23)_8,"Between the guests on May 13 , who is younger ?",```python\n# Define the table including the he...,Christopher Paul Colfer,ERROR,christopher paul colfer,chris colfer,40.000000,0.0
997,997,997,1001,List_of_Virtual_Console_games_for_Nintendo_3DS...,Which title had the earlier release date ? Was...,```python\n# Define the table including the he...,Qix,"('Avenging Spirit', 'None of the above')\n",qix,double dragon,0.000000,0.0
512,512,512,514,2003_Nationwide_Tour_0,How much prize money was shared among the runn...,```python\n# Define the table including the he...,"$ 615,000",375000.0\n,615000.0,not enough information provided,0.000000,0.0
1169,1169,1169,1176,List_of_Impulse_Reactor_and_Goo_games_1,What is the release date for the title that wa...,```python\n# Define the table including the he...,"June 2 , 2009","June 2 , 2009\n","june 2 , 2009","june 2, 2009",100.000000,100.0
652,652,652,655,Carol_Wayne_1,Which channel aired reruns of the series in wh...,```python\n# Define the table including the he...,Comedy Central,Comedy Central\n,comedy central,comedy central,100.000000,100.0
611,611,611,614,List_of_Ukrainian_composers_4,What is the origin name of the derived city na...,```python\n# Define the table including the he...,Kyi,ERROR,kyi,not enough information provided,0.000000,0.0
758,758,758,762,List_of_whistleblowers_2,In what year did the individual leave intellig...,```python\n# Define the table including the he...,1977,1981\n,1977,1981,0.000000,0.0
533,533,533,535,Dancing_with_the_Stars_(U.S._season_1)_3,Who was did the person with the most points in...,```python\n# Define the table including the he...,J. Peterman,John O'Hurley\n,j. peterman,john o'hurley,0.000000,0.0
854,854,854,858,List_of_ECAC_Hockey_Student-Athlete_of_the_Year_0,What is the name of the home arena of the team...,```python\n# Define the table including the he...,Cheel Arena,ERROR,cheel arena,not enough information provided,0.000000,0.0
434,434,434,436,2002_Italian_Grand_Prix_0,what is the lap time of the driver born 3 Janu...,```python\n# Define the table including the he...,1:20.521,1:20.521\n,1:20.521,1:20.521,100.000000,100.0
880,880,880,884,List_of_Masonic_buildings_in_the_United_States_13,"For the building in Aurora , in what month was...",```python\n# Define the table including the he...,October,ERROR,october,october,100.000000,100.0
1108,1108,1108,1115,1920_International_Cross_Country_Championships_0,"For the longest time clocked , what is the nam...",```python\n# Define the table including the he...,the United Kingdom,"('Archie Craig Sr', 'Scotland')\n",the united kingdom,"archie craig sr, scotland",0.000000,0.0
4,4,4,4,Roger_Crozier_Saving_Grace_Award_1,How many Vezina Trophies did the most recent w...,```python\n# Define the table including the he...,six,6\n,6.0,6.0,100.000000,100.0
1390,1390,1390,1399,Wikimania_0,How many people live in the metropolitan area ...,```python\n# Define the table including the he...,2.4 million,ERROR,2.4,not enough information provided,0.000000,0.0

## LLama 3 FETAQA

In [20]:
llama3_feta = pd.read_csv('/Users/harshavardhank/Desktop/Code/UPenn/TTQA-Recasting/Benchmark/src/scripts/models/responses/llama3-70b-8192/fetaqa/faithful_results.csv')
llama3_feta.sample(50)

,Unnamed: 0,index,table_id,question,response,answer,output
443,443,443,totto_source/dev_json/example-1837.json,What games did Pelle Rietveld participate in 2...,Here is the Python code to answer the question...,"In 2013, Pelle Rietveld competed at the Europe...",ERROR
856,856,856,totto_source/dev_json/example-437.json,What is Deep: 15th Impact?,Here is the Python code with reasoning to answ...,"Deep: 15th Impact was an event held on July 3,...",The winner of the 2018 election is Green with ...
874,874,874,totto_source/dev_json/example-1787.json,Where did Damien Perinelle play after playing ...,Here is the Python code to answer the question...,After playing for Istres in Ligue 2 in the 201...,Damien Perrinelle played for New York Red Bull...
162,162,162,totto_source/train_json/example-7071.json,Who was the winner and what was the majority i...,Here is the Python code with reasoning to answ...,"The winner, Liberal candidate William Mather, ...",The winner of the 1889 Gorton by-election was ...
546,546,546,totto_source/train_json/example-13996.json,How many years did Whitey Baccus coach for SMU...,Here is the Python code with reasoning to answ...,Whitey Baccus was a coach to SMU for six seaso...,Whitey Baccus coached for SMU for 6 seasons an...
1037,1037,1037,totto_source/train_json/example-13188.json,How many goals and appearances did Mirco Anten...,Here is the Python code to answer the question...,Mirco Antenucci scored 19 goals in 41 appearan...,ERROR
860,860,860,totto_source/dev_json/example-382.json,What's Dave Harold's second ranking final?,Here is the Python code to answer the question...,Dave Harold reached his second ranking final i...,Jim Hinga's coaching record is 154-169 (.477)\n
470,470,470,totto_source/train_json/example-13193.json,What awards did Channing win in 1964?,Here is the Python code to answer the question...,"In 1964, Channing won a Tony Award for Best Ac...",Channing won the Tony Award for Best Actress i...
1096,1096,1096,totto_source/train_json/example-1502.json,Were many applicants admitted to California Po...,Here is the Python code to answer the question...,"In 2017, 16,695 freshmen were accepted out of ...","Yes, many applicants were admitted to Californ..."
1381,1381,1381,totto_source/dev_json/example-1677.json,Did the D'Ambrosio twins appear together follo...,Here is the Python code to answer the question...,"In 2013, The D'Ambrosio Twins starred in the F...","In 2013, the D'Ambrosio twins appeared togethe..."
1123,1123,1123,totto_source/train_json/example-1827.json,What were Clinton Portis' best times?,Here is the Python code to answer the question...,Clinton Portis recorded personal best of 6.93 ...,Clinton Portis' best times are 60 meters in 6....
686,686,686,totto_source/dev_json/example-760.json,What is the GT model of the Ford Mustang since...,Here is the Python code with reasoning to answ...,The GT model continued with the 260 hp (194 kW...,The GT model of the Ford Mustang since 1999 is...
1032,1032,1032,totto_source/train_json/example-4856.json,How many votes out of how many did the winner ...,Here is the Python code to answer the question...,Risto Ryti received 269 of the 300 votes.,ERROR
620,620,620,totto_source/train_json/example-449.json,How much did the total forfeitures change from...,Here is the Python code with reasoning to answ...,"From 2005 to 2010, the forfeitures went from $...",1.25\n
278,278,278,totto_source/train_json/example-13934.json,What were Rolanda Vera's personal records at t...,Here is the Python code to answer the question...,Rolando Vera doubled up at the 1989 Bolivarian...,"{'5000 m': '14:24.64', '10,000 m': '29:54.22'}\n"
875,875,875,totto_source/train_json/example-1896.json,"After 2008, how did Notre Dame do in the Great...",Here is the Python code to answer the question...,"The following year, in 2009, Notre Dame again ...",ERROR
7,7,7,totto_source/train_json/example-7363.json,What significant career achievement did Yu mak...,Here is the Python code to answer the question...,"In 2011 Yu was noted for Palace, which earned ...","Won three awards: Most Popular Screenwriter, B..."
1043,1043,1043,totto_source/train_json/example-765.json,In what years was the member of the Legislativ...,Here is the Python code to answer the question...,The Communist Party of India represented the C...,ERROR
1448,1448,1448,totto_source/dev_json/example-1935.json,What did David Storl achieve in 2011?,Here is the Python code to answer the question...,"In 2011, David Storl topped the podium at the ...",ERROR
569,569,569,totto_source/train_json/example-3032.json,What was the best-selling album in the U.S. be...,Here is the Python code to answer the question...,Their Greatest Hits was the best-selling album...,ERROR
133,133,133,totto_source/dev_json/example-442.json,What role did Rebolledo play in 2000?,Here is the Python code to answer the question...,"In 2000, Rebolledo appeared as Lt. Orra on the...",ERROR
784,784,784,totto_source/train_json/example-13975.json,"What year was Pale Waves' music video for ""Tel...",Here is the Python code to answer the question...,"Pale Waves´ second music video, ""Television Ro...",The music video for 'Television Romance' was r...
391,391,391,totto_source/train_json/example-2183.json,How many goals did Boško Balaban score on Marc...,Here is the Python code to answer the question...,Boško Balaban played in the Croatian team's qu...,ERROR
513,513,513,totto_source/train_json/example-2720.json,Did Grease set a record for longest performanc...,Here is the Python code to answer the question...,"Closed in 1980, Grease's 3,388-performance run...",ERROR
165,165,165,totto_source/train_json/example-4704.json,In what year did St Clement win a Lifetime Ach...,Here is the Python code to answer the question...,"In 2012, St Clement won a Lifetime Achievement...",2012\n
1203,1203,1203,totto_source/train_json/example-13638.json,Which of Stir's singles charted in 2000 and wh...,Here is the Python code to answer the question...,"The two singles from Holy Dogs, ""New Beginning...",The singles that charted in 2000 are:\n
365,365,365,totto_source/dev_json/example-1402.json,In what roles in what television series did Ja...,Here is the Python code with comments to answe...,"In 2017, Sinclair starred as Amber in Easy and...",ERROR
1022,1022,1022,totto_source/dev_json/example-2.json,Who is the best performing player in 1906 Bost...,Here is the Python code to answer the question...,"In the 1906 Boston Americans season, Jesse Tan...",ERROR
993,993,993,totto_source/dev_json/example-1367.json,What did Emilio Osorio play in 2015?,Here is the Python code to answer the question...,"In 2015, Emilio Osorio played a role in the se...",ERROR
842,842,842,totto_source/dev_json/example-2115.json,Who won the 1888 Belgian general election?,Here is the Python code to answer the question...,The result was a victory for the Catholic Part...,The Catholic Party won the 1888 Belgian genera...
1518,1518,1518,totto_source/dev_json/example-651.json,"Who did Merrells cast in ""Knightfall"" in 2017?",Here is the Python code to answer the question...,Merrells was cast as Tancrede de Hautville in ...,Tancrede de Hautville\n
1146,1146,1146,totto_source/train_json/example-3859.json,How successful was AIK Handboll in 1951 and 1952?,Here is the Python code to answer the question...,AIK Handboll won the Swedish Championship in 1...,"In 1951, They won. In 1952, They lost.\n"
1492,1492,1492,totto_source/train_json/example-13732.json,When did Don Peden begin and end his career wi...,Here is the Python code to answer the question...,Don Peden compiled a record of 121–46–11 with ...,Don Peden began his career with the Ohio Bobca...
969,969,969,totto_source/train_json/example-13538.json,"While Clough played with Middlesbrough, how ma...",Here is the Python code to answer the question...,Brian Clough scored 204 goals in 222 league ma...,ERROR
1162,1162,1162,totto_source/train_json/example-5.json,How many times has Ekaterina Bushueva won the ...,Here is the Python code with reasoning to answ...,Ekaterina Bushueva has won the Women's World D...,ERROR
1238,1238,1238,totto_source/dev_json/example-1918.json,How did Mauricio Ortega perform in the 2013 So...,Here is the Python code to answer the question...,Mauricio Ortega in South American junior champ...,Mauricio Ortega performed 1st with a distance ...
1327,1327,1327,totto_source/train_json/example-2906.json,What full-length film roles did Molly Burnett ...,Here is the Python code to answer the question...,"In 2013, Molly Burnett portrayed Ashley Bloom ...",ERROR
1010,1010,1010,totto_source/train_json/example-4923.json,What role did Tati Alcantara have in Cabaret a...,Here is the Python code to answer the question...,"In 2009, Tati Alcántara acted in Cabaret as Lulu.",ERROR
746,746,746,totto_source/train_json/example-1887.json,Who were the slowest 3 finishers of the Women'...,Here is the Python code to answer the question...,Great Britain's Jemma Lowe finished with a tim...,"The slowest 3 finishers were Jemma Lowe, Gabri..."
468,468,468,totto_source/train_json/example-3043.json,What roles did Marco Pigossi play in 2007-2008?,Here is the Python code to answer the question...,"In 2007, Marco Pigossi participated in Eterna ...","['Miguel Finnegan', 'Bruno']\n"
692,692,692,totto_source/dev_json/example-1243.json,What did Goth play in 2017?,Here is the Python code to answer the question...,"In 2017, Goth played in the film A Cure for We...",Goth played Hannah von Reichmerl in A Cure for...
900,900,900,totto_source/train_json/example-271.json,"At the 2009 World Championships in Athletics,...",Here is the Python code to answer the question...,Tadese took silver with a run time of 26:50.12...,The silver medalist is Zersenay Tadese and the...
404,404,404,totto_source/train_json/example-13312.json,What were the results of the 1967 San Diego ma...,Here is the Python code to answer the question...,"In the 1967 San Diego mayoral election, Curran...",The results of the 1967 San Diego mayoral elec...
920,920,920,totto_source/train_json/example-13921.json,When was Jayne Houdyshell nominated for her fi...,Here is the Python code to answer the question...,Jayne Houdyshell was nominated for the 2016 Ou...,Jayne Houdyshell was nominated for her first O...
1093,1093,1093,totto_source/train_json/example-161.json,What role did Sterling Jerins reprise in any o...,Here is the Python code to answer the question...,"In 2016, Sterling Jerins reprised her role as ...",Sterling Jerins reprised the role of Judy Warr...
1377,1377,1377,totto_source/train_json/example-4412.json,Who competed in the 800 m at the 2001 World Ch...,Here is the Python code to answer the question...,Isireli Naikelekelevesi competed in the 800 m ...,ERROR
34,34,34,totto_source/train_json/example-13556.json,When did Anthony Alonzo win Metro Manila Film ...,Here is the Python code to answer the question...,Anthony Alonzo won the Best Actor awards from ...,ERROR
124,124,124,totto_source/train_json/example-9052.json,What was the competition name and Fuamatu's po...,Here is the Python code to answer the question...,"Fuamatu won silver at the 2011 Pacific Games, ...",The competition name was Oceania Championships...
1380,1380,1380,totto_source/train_json/example-1406.json,Did Allison Stokke improve every year from 201...,Here is the Python code to answer the question...,Allison Stokke's performance declined from 201...,False\n
1087,1087,1087,totto_source/train_json/example-9340.json,"What was the name, category, year and nominate...",Here is the Python code to answer the question...,Alexx Ekubo won the Best Supporting Actor awar...,The name of the award is Golden Icons Academy ...

In [9]:
import pandas as pd
finqa = pd.read_csv('/Users/harshavardhank/Desktop/Code/UPenn/TTQA-Recasting/Benchmark/src/scripts/models/responses/New/meta_new_2/finqa_meta_results.csv')

In [8]:
filtered_rows = finqa[finqa['f1_score'] < 50]
filtered_rows.sample(40)

,Unnamed: 0.1,Unnamed: 0,index,table_id,question,response,answer,output,conv_actual_answer,conv_predicted_answer,f1_score,exact
33,33,33,33,Table_34,"as of december 31 , 2017 what was the value of...",## Decomposition:\n \n sq1. What is the valu...,9294571.92,$58.02 \n,9294571.92,58.02,0.0,0.0
771,771,771,771,Table_772,what was the percentage rent increase between ...,## Decomposition:\n\n**sq1.** What was the tot...,5%,4.9% \n,0.05,0.049,0.0,0.0
70,70,70,70,Table_71,brazilian paper sales represented what percent...,## Decomposition:\n \n sq1. What is the tota...,7%,Cannot be calculated. \n,0.07,cannot be calculated,0.0,0.0
134,134,134,134,Table_135,"what was the average total revenue in 1999 , 2...",## Decomposition:\n\n**sq1:** What is the tota...,231341.7,Not enough information provided. \n,231341.7,not enough information provided,0.0,0.0
84,84,84,84,Table_85,what was the decrease in rental expense ( mill...,## Decomposition:\n\n**sq1.** What was the ren...,NaN,9 million \n,NaN,9.0,0.0,0.0
785,785,785,785,Table_786,"as of december 2013 and december 2012 , what w...",## Decomposition:\n\n**sq1.** What was the ave...,179.35,354.745 \n,179.35,354.745,0.0,0.0
919,919,919,919,Table_920,what was the cumulative rent expense from 2004...,## Decomposition:\n**sq1.** What is the total...,658,Not enough information provided. \n,658.0,not enough information provided,0.0,0.0
340,340,340,340,Table_341,what portion of the future minimum lease payme...,## Decomposition:\n\n**sq1.** What is the valu...,19.4%,"$11,057 \n",0.19399999999999998,11057.0,0.0,0.0
2,2,2,2,Table_3,what was the difference in percentage cumulati...,## Decomposition:\n \n sq1. What was the cum...,NaN,54.2% \n,NaN,0.542,0.0,0.0
468,468,468,468,Table_469,what was the percentage change in net sales fo...,## Decomposition:\n\n**sq1.** What was the net...,-14%,-13.65%\n,-0.14,-0.1365,0.0,0.0
331,331,331,331,Table_332,considering the average exercise price of opti...,## Decomposition:\n\n**sq1:** What is the numb...,241.11,Not enough information provided. \n,241.11,not enough information provided,0.0,0.0
402,402,402,402,Table_403,what was the percentage decline in the operati...,"```json\n{\n ""decomposition"": [\n ""sq1. What ...",-83.3%,83% \n,-0.833,0.83,0.0,0.0
736,736,736,736,Table_737,in 2008 what was the ratio of the trading asse...,## Decomposition:\n\n**sq1.** What was the val...,1.72,1.30\n,1.72,1.3,0.0,0.0
196,196,196,196,Table_197,the company purchased how much in millions dur...,## Decomposition:\n\n**sq1.** What is the valu...,36.9,3.772 \n,36.9,3.772,0.0,0.0
308,308,308,308,Table_309,for the periods 10/01/04 2013 10/31/04 and 11/...,## Decomposition:\n\n**sq1:** What was the ave...,39.73,"$40.51, $38.94 \n",39.73,"40.51, 38.94",0.0,0.0
748,748,748,748,Table_749,"in years , what is the average contractual ter...",## Decomposition:\n\n**sq1:** What is the cont...,2.9266,2.93 years\n,2.9266,2.93 years,0.0,0.0
701,701,701,701,Table_702,what was the difference in percentage five-yea...,## Decomposition:\n\n**sq1.** What was the fiv...,-22%,9.32% \n,-0.22,0.0932,0.0,0.0
157,157,157,157,Table_158,considering the average exercise price of opti...,## Decomposition:\n\n**sq1.** What is the tota...,16.43,Not enough information provided. \n,16.43,not enough information provided,0.0,0.0
122,122,122,122,Table_123,what is the total return if 100000 are investe...,## Decomposition:\n\n**sq1.** What is the cumu...,3829,"38,290\n",3829,"38,290",0.0,0.0
500,500,500,500,Table_501,what was total liability reflected as other lo...,## Decomposition:\n\n**sq1.** What was the bal...,121321,"180993, 158578 \n",121321.0,"180993, 158578",0.0,0.0
436,436,436,436,Table_437,what is the net income per common share in 2008?,## Decomposition:\n\n**sq1.** What is the basi...,.385,0.385 \n,385.0,0.385,0.0,0.0
356,356,356,356,Table_357,what will be the balance of aggregate carrying...,## Decomposition:\n\n**sq1.** What is the valu...,4331309,1837000 thousand \n,4331309.0,1837000 thousand,0.0,0.0
184,184,184,184,Table_185,"as of december 31 , 2005 , what was the before...",## Decomposition:\n\n**sq1.** What was the cha...,31,19 million \n,31.0,19.0,0.0,0.0
61,61,61,61,Table_62,"as of december 31 , 2007 , how much unrecogniz...",## Decomposition:\n\n**sq1.** What is the valu...,26.4,Not enough information provided. \n,26.4,not enough information provided,0.0,0.0
597,597,597,597,Table_598,what was the average basic net income availabl...,## Decomposition:\n\n**sq1. What were the basi...,139801,139.801 \n,139801.0,139.801,0.0,0.0
357,357,357,357,Table_358,what was the percent of the outstanding notes ...,## Decomposition:\n\n**sq1:** What was the out...,81.3%,-18.73% \n,0.813,-0.1873,0.0,0.0
929,929,929,929,Table_930,in 2007 what was the percent of the total debt...,## Decomposition:\n\n**sq1.** What was the tot...,21.9%,27.9% \n,0.21899999999999997,0.27899999999999997,0.0,0.0
680,680,680,680,Table_681,what was the percent of the aggregate restruct...,## Decomposition:\n- **sq1:** What is the tota...,55.3%,67.31% \n,0.5529999999999999,0.6731,0.0,0.0
843,843,843,843,Table_844,what was the percentage change in the weighted...,## Decomposition:\n\n**sq1.** What was the wei...,NaN,58.97% \n,NaN,0.5897,0.0,0.0
795,795,795,795,Table_796,what is the net income per common share for th...,## Decomposition:\n\n**sq1.** What is the net ...,NaN,1.56 \n,NaN,1.56,0.0,0.0
183,183,183,183,Table_184,what is the average expected dividend per shar...,## Decomposition:\n\n**sq1:** What is the expe...,1.4,$1.37 \n,1.4,1.37,0.0,0.0
248,248,248,248,Table_249,what is the percentage change in the total not...,## Decomposition:\n\nThis question cannot be a...,10.8%,Not enough information provided. \n,0.10800000000000001,not enough information provided,0.0,0.0
632,632,632,632,Table_633,what was the tax rate applied applied to the g...,## Decomposition:\n\n**sq1. What was the total...,10.3%,0.90625 \n,0.10300000000000001,0.90625,0.0,0.0
372,372,372,372,Table_373,what is the net change of the total fair value...,## Decomposition:\n\n**sq1. What is the total ...,6820,"$6,900 thousand \n",6820,"6,900 thousand",0.0,0.0
855,855,855,855,Table_856,in 2015 what was the percent of the total oper...,"```json\n{\n ""decomposition"": [\n ""sq1. What ...",17.4%,16.22% \n,0.174,0.16219999999999998,0.0,0.0
861,861,861,861,Table_862,what is the difference of between the carrying...,## Decomposition:\n\n**sq1.** What is the carr...,27,$114 million \n,27.0,114.0,0.0,0.0
63,63,63,63,Table_64,what percentage of the company's gross liabili...,## Decomposition:\n\n**sq1:** What is the comp...,41.1%,Not enough information provided. \n,0.41100000000000003,not enough information provided,0.0,0.0
267,267,267,267,Table_268,what was the percentage change in level 3 fina...,## Decomposition:\n\n**sq1.** What was the val...,-18%,-17.5% \n,-0.18,-0.175,0.0,0.0
13,13,13,13,Table_14,"in 2010 and 2009 , what was the total fair val...",## Decomposition:\nThis question is unanswerab...,68.9,Not enough information provided. \n,68.9,not enough information provided,0.0,0.0
365,365,365,365,Table_366,what was the percent of the change of the weig...,## Decomposition:\n\n**sq1.** What was the wei...,-21%,-20.67% \n,-0.21,-0.20670000000000002,0.0,0.0